#!/bin/tcsh -f

# sourceme: set global env parameters
source ../ut/export.csh

# run dc shell
if ($1 == "debug") then
    dc_shell -gui
else if ($1 == "syn") then
    dc_shell -f run.tcl | tee -i run.log
endif

